### ISSUE TITLE
IRA：Whether staID and location information are in dqpsk？

### ISSUE THREAD

**Issue by cyqsir** [muccc/iridium-toolkit#109] opened 2024-03-25 13:44 UTC
Whether staID and location information are in dqpsk？Is the timestamp decoded or added manually？Whether bpsk is useless for decoding IRA？Whether there is documentation for the code package detailed description？
Thank you for your answer！

**Comment by schneider42** [comment] 2024-03-25 14:29
Duplicate of https://github.com/muccc/gr-iridium/issues/192

**Closed by schneider42** 2024-03-25 14:29 UTC
